### ISSUE TITLE
Uncatchable error

### ISSUE THREAD

**Issue by maskalix** [zyrouge/node-genius-lyrics#26]
Hi, 
I have problem with error "NoResultError: No result was found"
If its unable to find a lyric it returns a error message which can't be catched and terminates the node process.
For example I tried this input "Aim Vision - Have You Seen The Moon Tonight?" and it gives the error mentioned above.

How can I solve that error? 

Thanks,
Martin Skalicky

**Comment by zyrouge** [comment]
Can you send the code?

**Comment by zyrouge** [comment]
Solved this is discord. Closing this.
