### ISSUE TITLE
403 - Error, wrong url?

### ISSUE THREAD

**Issue by verbindolai** [zyrouge/node-genius-lyrics#27]
Im having issues when trying to get the songs from an artist, im always getting an 403 Error with the message "Action forbidden for current scope". 

I think it's because the url called looks like this: `api.genius.com/songs?page=1&per_page=20&sort=title`,
But shouldn't it look more like this `api.genius.com/artist/1234567/songs?page=1&per_page=20&sort=title` ?

https://github.com/zyrouge/node-genius-lyrics/blob/f90c6c8ec7cb8b154a704231052b77c9ae4c48cf/lib/artists/artist.ts#L103-L106

I changed this block to use the correct url and fixed access to the response like this:
```javascript
...
const data = await this.client.api.get(
      `/artists/${this.id}/songs?page=${nOptions.page}&per_page=${nOptions.perPage}&sort=${nOptions.sort}`
);
const parsed = JSON.parse(data).response; // Added the .response
...
```
And it works for me. 
Did i found a bug or am i just missing something?

**Comment by zyrouge** [comment]
It's probably me who messed up. I'll push a fix.
