### ISSUE TITLE
tracklyrics.lyrics() is not a function

### ISSUE THREAD

**Issue by yungbeatz** [zyrouge/node-genius-lyrics#29]
I am following the example in the README, although while using it in my code, my console says that `tracklyrics.lyrics` is not a function.
I am trying to make a command in Discord.js with it so whenever my bot plays a song, the users can get the lyrics of the current song that is playing.

This is how I am using the package:
```js
const queue = await client.distube.getQueue(interaction.guildId);
const tracklyrics = queue.songs[0];
const lyrics = await tracklyrics.lyrics();

//Everything down below shouldn't be relevant to the error. 

//response.setAuthor({ name: "LYRICS", iconURL: user.avatarURL({ dynamic: true }) })
//response.setDescription("**_ Sent Lyrics to your DMs_**")
//user.send({ embeds: [new MessageEmbed().setColor("#2F3136").setAuthor({ name: "LYRICS", iconURL: //user.avatarURL({ dynamic: true }) }).setDescription(`${lyrics}`)] });
//return interaction.reply({ embeds: [response] });

**Comment by zyrouge** [comment]
May I know what `queue.songs` is? If it isn't an instance of `Song` from `genius-lyrics` package, it's not going to work.
