### ISSUE TITLE
Instrumental songs give a "no result" error

### ISSUE THREAD

**Issue by Jelmerro** [zyrouge/node-genius-lyrics#31]
The lyrics are checked to have "length", which means as much as having any content, but an instrumental song does not have lyrics. The string is empty: https://github.com/zyrouge/node-genius-lyrics/blob/next/lib/songs/song.ts#L93 and thus passes the loop and throws an error. I would like an option to know if a song is instrumental, either by return this or with a separate function to check for elements like this on the page:
![image](https://user-images.githubusercontent.com/1696674/184173521-657e456d-c362-4735-80ca-a010ee2eabe6.png)

**Comment by zyrouge** [comment]
Can you link me an instrumental song that has no lyrics?

**Comment by Jelmerro** [comment]
Just as an example, but there are many more obviously: https://genius.com/Camel-beached-lyrics
