### ISSUE TITLE
NoResultError for some specific queries

### ISSUE THREAD

**Issue by Jelmerro** [zyrouge/node-genius-lyrics#33]
This library works wonderfully for most queries, but some are problematic. I have not found a cause for it yet, but it happens occasionally with some queries, it's always the same result, so it is consistent in that sense. This never gives results no matter how often I retry it, I can also try rewording it, it just does not show results when searching for this song in particular. Good to note, is that it's also the name of the album, so perhaps something is going wrong with that. I can fetch every single other song by the doors, just not this one.
![image](https://user-images.githubusercontent.com/1696674/184177619-a40a96ef-b187-4f8c-99c4-97bd626d4106.png)
![image](https://user-images.githubusercontent.com/1696674/184177756-9a2983cd-b693-4ed5-a96a-05c7b148351e.png)

**Comment by zyrouge** [comment]
Aight, I'll look into it asap.

**Comment by zyrouge** [comment]
🎉 Patched in v4.4.0! I'll also go ahead and close #32 and #33 since I have implemented a fix for those as well.

**Comment by Jelmerro** [comment]
Thanks for the new release, it works really well! :tada:
