### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'hits')

### ISSUE THREAD

**Issue by warior456** [zyrouge/node-genius-lyrics#36]
at SongsClient.<anonymous> (H:\discordbot\mrdia-main\node_modules\genius-lyrics\dist\songs\client.js:43:42)
    at Generator.next (<anonymous>)
    at fulfilled (H:\discordbot\mrdia-main\node_modules\genius-lyrics\dist\songs\client.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by warior456** [comment]
am i doing something wrong or what?

**Comment by zyrouge** [comment]
> This is actually still relevant, I'm getting this error when using `(await Genius.songs.search(title))[0]`.

Could you send the whole code and the steps to reproduce this error?

**Comment by MeridianGH** [comment]
Sure, this is my code without the unneccessary parts:
```js
const Genius = new genius.Client(geniusClientToken)
try {
    const song = (await Genius.songs.search(title))[0]
    const lyrics = await song.lyrics()
    // Process lyrics here
} catch {
    // Send error here
}
```
`geniusClientToken` is a string containing my key.
`title` is a valid string that contains the artist name and song title.

However, I was just testing a bit, and this apparently works fine without a key.
My key could possibly be invalid, but didn't earlier versions warn you about that?

**Comment by zyrouge** [comment]
> 

Could you give the value of title so that I'll check if that occurs. The tests seems to pass just fine.

**Comment by zyrouge** [comment]
> ~Could you give the value of title so that I'll check if that occurs. The tests seems to pass just fine.~ I'll check if invalid key causes that.

Seems like I couldn't reproduce this issue. Could you give the `title` used in that code?

**Comment by MeridianGH** [comment]
I had the error occur with every `title` I entered. Turns out the issue was indeed an invalid key though, weirdly enough.

**Comment by zyrouge** [comment]
API related errors are now handled.
