### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by LoryPelli** [zyrouge/node-genius-lyrics#37]
It happens only with my host, not with Visual Studio Code

**Comment by zyrouge** [comment]
Host? What host do you mean? Hosting service?

**Comment by LoryPelli** [comment]
> Host? What host do you mean? Hosting service?

my hosting is
https://client.apexcloud.be

**Comment by LoryPelli** [comment]
I'm using it for a bot discord, where I run the bot from the host, when I try to search lyrics it does this error, but if I run the bot locally (VSCode) it doesn't

**Comment by zyrouge** [comment]
> I'm using it for a bot discord, where I run the bot from the host, when I try to search lyrics it does this error, but if I run the bot locally (VSCode) it doesn't

Use a proxy since the website blocks some ips to prevent scraping website.
