### ISSUE TITLE
Lyrics not working

### ISSUE THREAD

**Issue by Tomato6966** [zyrouge/node-genius-lyrics#40]
This is my initialization:

```js
const lyrics = new Genius.Client(process.env.GENIUSTOKEN);
```

this is my command:

```js
lyrics.songs.search("Omfori Skidder Skidder Skidder").then(async x => {
          return x?.length ? await x[0].lyrics() : null;
}); 
```

This is the output:

```
Error: No result was found
```

It is because this happens when u fetch the uri:
https://milrato.com/codeshare/code/63a41dd1b7ad972a43f9380a

But when I open it in the BROWSER of the SERVER where I'M making the request of, it does not show cloudflare:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/68145571/209098960-584c8bf7-7e0d-4050-88a4-5dcff13a8c29.png">

Please make it possible to change browser origin headers.
So I can use the ones from my BROWSER (Firefox, linux, etc.) (defaultUserAgent )
because I'd need: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0`
+ maybe cookies could help?

cause lyrics you scrape

**Comment by Tomato6966** [comment]
just changing the defaultUserAgent, did not fix it
maybe cookies could?

**Comment by zyrouge** [comment]
> just changing the defaultUserAgent, did not fix it maybe cookies could?

Maybe. Cloudflare checks are not easy to bypass afaik.

**Comment by Tomato6966** [comment]
It's not really a cloudflare check, it's more a google captcha

**Comment by zyrouge** [comment]
> It's not really a cloudflare check, it's more a google captcha

No, it's actually Cloudflare Captcha.

**Comment by Tomato6966** [comment]
Okay

**Comment by Tomato6966** [comment]
If you could show me where to insert what, to test cookies, I can test it

**Comment by zyrouge** [comment]
Sample code for setting headers:
```js
new Genius.Client("your_token", {
        requestOptions: {
            headers: {
                "user-agent": "your_custom_user_agent",
                cookie: "cookies",
            }
        }
    })
```

**Comment by Tomato6966** [comment]
using cookies, doesnt fix it either

hmmm
since I'm on ovh, I can't get lyrics anymore... sadge

**Comment by Tomato6966** [comment]
Imma build some sort of a proxy cache wrapper then..
> Thanks tho.

**Comment by zyrouge** [comment]
Closing this since this can't be fixed.
