### ISSUE TITLE
Reversal of the thumbnail and profile image

### ISSUE THREAD

**Issue by Mylloon** [zyrouge/node-genius-lyrics#43]
The thumbnail returns the image of the artist and the image returns the thumbnail

https://github.com/zyrouge/node-genius-lyrics/blob/9330e288ee7301d33fb7ed8aff236cbef8616a6c/lib/artists/artist.ts#L46-L47

Tell me if its a bug I can submit a PR

**Comment by zyrouge** [comment]
> The thumbnail returns the image of the artist and the image returns the thumbnail
> 
> https://github.com/zyrouge/node-genius-lyrics/blob/9330e288ee7301d33fb7ed8aff236cbef8616a6c/lib/artists/artist.ts#L46-L47
> 
> Tell me if its a bug I can submit a PR

Doesn't `image_url` have a 1:1 ratio? That's probably why it is thumbnail. This was made when the library was primary used for Discord bots. Probably it now makes sense to switch it up. You can submit a PR for it.
