### ISSUE TITLE
switch to node-html-parser from cheerio

### ISSUE THREAD

**Issue by twlite** [zyrouge/node-genius-lyrics#46]
tldr; Switch to [node-html-parser](https://www.npmjs.com/package/node-html-parser) for better performance.

Genius Lyrics is used by [@discord-player/extractor](https://npm.im/@discord-player/extractor) and parsing lyrics usually seems to block the thread (which seems to be caused by cheerio). `node-html-parser` states that `Per the design, it intends to parse massive HTML files in lowest price, thus the performance is the top priority.`. Benchmark results show that `node-html-parser` is very fast compared to cheerio.

**Comment by zyrouge** [comment]
Done!
